<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\bubbles.ico</ApplicationIcon>
    <PackageIcon>Assets\bubbles-256.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BubblesCmd.Core\BubblesCmd.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EasyWindowsTerminalControl" Version="1.0.38" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\bubbles.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\bubbles-256.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
